[pytest]
asyncio_default_fixture_loop_scope = session
filterwarnings =
    ignore:'oneOf' deprecated - use 'one_of':pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:'parseString' deprecated - use 'parse_string':pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:'resetCache' deprecated - use 'reset_cache':pyparsing.exceptions.PyparsingDeprecationWarning
    ignore:'enablePackrat' deprecated - use 'enable_packrat':pyparsing.exceptions.PyparsingDeprecationWarning
